### ISSUE TITLE
Fiddler

### ISSUE THREAD

**Issue by bonxz** [lk3de/impftermin-checker#10]
Habe die andere Methode mit den Vermittlungscode und Fiddler probiert. Bekomme aber folgenden Fehler. Komme damit nicht weiter.

![fiddler](https://user-images.githubusercontent.com/61289944/118716952-b7b00900-b825-11eb-9511-b49d7825de14.png)

![fiddler 2](https://user-images.githubusercontent.com/61289944/118717170-01005880-b826-11eb-8ba4-670bbb2859ca.png)

**Comment by orSpec** [comment]
OnBeforeResponse is the correct function to edit.

**Comment by bonxz** [comment]
> OnBeforeResponse is the correct function to edit.

It is in this function. Just put it at the end. Even if I put it at the top it doesn't work and the same error appears.

**Comment by greg121** [comment]
`    static function OnBeforeResponse(oSession: Session) {
        if (m_Hide304s && oSession.responseCode == 304) {
            oSession["ui-hide"] = "true";
        }
        if (oSession.uriContains("impfterminservice") && oSession.uriContains("termincheck")) {
            oSession.utilSetResponseBody('{"termineVorhanden":true,"vorhandeneLeistungsmerkmale":["L921"]}')
        }
    }`

it should look like this right?

**Comment by bonxz** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/5558797/118848498-17162380-b8cf-11eb-9853-16e9350641ee.png)
> 
> it should look like this right?

Yea i got it to work. Thanks :)
