### ISSUE TITLE
Age vs Birthdate

### ISSUE THREAD

**Issue by trapilon** [lk3de/impftermin-checker#16]
Thank's for the script, I'm using it to find appointments for relatives.

When I manually used impfterminservice.de ~one month ago, the "Anspruchsprüfung" required users to provide an age, which is supported by your script.
However, the website now asks users to provide a birthday in _tt.mm.yyyy_ format when you get through clicking "Nein".

Just wanted to raise awareness on the difference, please close/delete this issue in case the script supports it already.

**Comment by lk3de** [comment]
Thank you for this finding! Indeed, the script doesn't support this (yet). Feel free to submit a PR in case you fixed that already for yourself 🙂

Probably you can use the [Recommended option to get a Vermittlungscode instantly (Windows-only)](https://github.com/lk3de/impftermin-checker#recommended-option-to-get-a-vermittlungscode-instantly-windows-only) in the meantime.

**Comment by trapilon** [comment]
> Feel free to submit a PR in case you fixed that already for yourself 🙂

Sorry, I'm not much of a coder myself.
