### ISSUE TITLE
"Get a Vermittlungscode instantly" not working anymore

### ISSUE THREAD

**Issue by ghac101** [lk3de/impftermin-checker#17]
Hey,
seems like "Recommended option to get a Vermittlungscode instantly (Windows-only)" is not working anymore, or can anyone explain how to do it?

I inserted the code in fiddler as described:

    static function OnBeforeResponse(oSession: Session) {
		if (oSession.uriContains("impfterminservice") && oSession.uriContains("termincheck")) {
			oSession.utilSetResponseBody('{"termineVorhanden":true,"vorhandeneLeistungsmerkmale":["L921"]}')
		}
        if (m_Hide304s && oSession.responseCode == 304) {
            oSession["ui-hide"] = "true";
        }
    }

But when visiting the page: https://357-iz.impfterminservice.de/impftermine/check
I get the error message: Schnellprüfung nicht erfolgreich.

Can anyone support please?
Thanks!

**Comment by SilvesterSchneider** [comment]
Seems like they changed something on the request.
Tried it also few days ago.
Just gettin a *Bad Request*.

**Comment by lk3de** [comment]
Change the Fiddler script to the following:

```
if (oSession.uriContains("/rest/suche/termincheck?plz")) {
    oSession.utilSetResponseBody('{"termineVorhanden":true,"vorhandeneLeistungsmerkmale":["L921"]}')
}

if (oSession.uriContains("/rest/suche/termincheck/alter")) {
    oSession.responseCode = 200;
    oSession.oResponse.headers.HTTPResponseCode = 200;
    oSession.oResponse.headers.HTTPResponseStatus = "200 OK";
    oSession.utilSetResponseBody('{"einzeltermineVorhanden":false,"terminpaareVorhanden":true}')
}
```

and additionally enable Rules -> Automatic Breakpoints -> After Responses.

You will need to manually click on every request in the Fiddler window and hit the "Run to Completion" button to complete the request.

I just tried it and it seems to work (let's see for how long). As an alternative, I also tried using https://github.com/iamnotturner/vaccipy today and that one worked as well - they can even book the appointment completely automated. Much better than my little script here, feel free to head over and try it out 🎉
