### ISSUE TITLE
Error while using

### ISSUE THREAD

**Issue by moonwhaler** [lk3de/impftermin-checker#18]
While executing "python3 impftermin_checker.py" I now get the following error:

Traceback (most recent call last):
  File "/Users/XXXXXX/Documents/impftermin/impftermin-checker/impftermin_checker.py", line 35, in <module>
    if config["use_chrome"]:
KeyError: 'use_chrome'

Before pulling the latest master it worked - except the cookie banner.

**Comment by lk3de** [comment]
Just add `"use_chrome": false` to your `config.json` :) This key was introduced with #14.

**Comment by moonwhaler** [comment]
This worked. Thanks!
