### ISSUE TITLE
Sound Alert requires an additional package on macOS

### ISSUE THREAD

**Issue by MeFisto94** [lk3de/impftermin-checker#6]
I don't have the exact stacktrace anymore, but you can easily find them via stackoverflow:
playsound complains about not being able to load the module `AppKit`, which is part of `PyObjC`, so adding that to the pip install line on macOS is crucial

**Comment by lk3de** [comment]
Unfortunately I have no MacOS device to test this 🙁 Can you confirm that the issue can be fixed via `pip3 install -U PyObjC`? Then we can add it to the readme 🙂

**Comment by fazzer4x** [comment]
Sadly I didn't hear anything when I revived a notification. I had PyObjC installed though. 

I did test on playsound() and it worked. Not quite sure why it didn't trigger. 

Maybe the system output and volume need to be set?

**Comment by lk3de** [comment]
> Maybe the system output and volume need to be set?

At least on Linux, `playsound()` just behaves as every media player would do and uses the standard system audio device and the current system volume as set by the user. Not sure if Mac OS behaves differently here.

**Comment by MeFisto94** [comment]
Yeah, I followed this advice: https://stackoverflow.com/q/47270354
I don't know if `AppKit` as a package is minimal enough, but certainly PyObjC did solve the issues (probably pulls in AppKit).

For me, playsound did work and I heard the sounds, actually the alarm is quite offensive, on full volume you can even hear it from the distance.

If direct playsound() works, maybe it was a user error? Like your volume was low at that point? It doesn't automatically bump the volume.
The only other alternative I could see is like if the e-mail works, but then there's an exception causing the script to not play a sound.
