### ISSUE TITLE
Random timings not working

### ISSUE THREAD

**Issue by fazzer4x** [lk3de/impftermin-checker#9]
I keep receiving this error and am not sure how to proceed. 

```
Unerwarteter Fehler ist 1x aufgetreten, breche ab.
Traceback (most recent call last):
  File "/Users/user/dev/impftermin-checker/impftermin_checker.py", line 80, in <module>
    waiting_time_dataset = config['waiting_time_between_each_dataset'] + randrange(5)
KeyError: 'waiting_time_between_each_dataset'
```

**Comment by fazzer4x** [comment]
ah, the config.json needs to be updated from wait_time* to waiting_time_*

**Comment by lk3de** [comment]
Argh, I think I introduced that with https://github.com/lk3de/impftermin-checker/commit/0d84279a31c1236b8403607523421068bec93ba1 - stupid mistake, sorry! 😀
